name: EPG Updater

on:
  schedule:
    - cron: '0 8 * * *'  # 08:00 UTC
    - cron: '0 20 * * *' # 20:00 UTC
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, libxml, simplexml, curl
        
    - name: Run EPG Script
      env:
        API_URL: ${{ secrets.API_URL }}
        EPG_URLS: ${{ secrets.EPG_URLS }}
      run: php epg-script.php
      
    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add epg.xml
        git diff --quiet && git diff --staged --quiet || git commit -m "Atualização automática do EPG"
        git push
